### ISSUE TITLE
deserialize() does not consume payload bytes of unknown fields

### ISSUE THREAD

**Issue by jchia** [Embedded-AMS/EmbeddedProto#27] opened 2021-11-01 03:29 UTC
When a field id is encountered that is not defined in the .proto file, deserialize() does not consume the payload bytes that follow and instead treats the first payload byte as the start of the next field and continues processing of the fields.

deserialize() should skip the payload bytes before trying to process the next field.

**Comment by BartHertog** [comment] 2021-11-01 08:05
Hello @jchia,

Thank you for writing in this issue. I saw the previous issue coming by and I greatly appreciate you looking further and making this ticket. It is very likely we will be looking at this issue this week.

Best regards,

Bart

**Comment by BartHertog** [comment] 2021-11-02 18:53
Hello @jchia,

The issue is fixed in version 2.3.3. The code is now available. If you have any remarks let me know.

Best regards,
Bart

**Closed by BartHertog** 2021-11-02 18:53 UTC

**Comment by jchia** [comment] 2021-11-03 04:18
Thanks, from reading the related code, I have written #28 and #29.
